name: Gatsby Publish

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Gatsby site
        run: npm run build

      - name: Add CNAME file
        run: echo "winter-love.dev" > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
